import {
  Baseline,
  Crop,
  Database,
  FileBraces,
  FileDown,
  FileUp,
  Fingerprint,
  Image,
  Link2,
  Maximize,
  PaintBucket,
  Palette,
  QrCode,
  Rainbow,
  Shield,
  SquaresUnite,
  SwatchBook,
  ToolCase,
  Triangle,
  Type,
  WholeWord,
} from 'lucide-react';
import { BsShadows } from 'react-icons/bs';
import { LuFileJson2, LuImageDown } from 'react-icons/lu';
import { PiImagesSquareBold, PiPlaceholder } from 'react-icons/pi';
import {
  SiCss,
  SiDart,
  SiElixir,
  SiGooglebigquery,
  SiGraphql,
  SiHtml5,
  SiJavascript,
  SiJson,
  SiJss,
  SiMarkdown,
  SiMongoose,
  SiMysql,
  SiPhp,
  SiPython,
  SiReact,
  SiReadthedocs,
  SiRust,
  SiSass,
  SiSharp,
  SiSvg,
  SiTailwindcss,
  SiToml,
  SiTypescript,
  SiYaml,
  SiZod,
} from 'react-icons/si';
import {
  TbBackground,
  TbBrandGolang,
  TbFileTypeJsx,
  TbNumber64Small,
  TbReplace,
} from 'react-icons/tb';
import { NavigationManager } from './utils';

export const NAVIGATION = new NavigationManager([
  {
    label: 'Color Tools',
    path: '/color-tools',
    icon: <Palette />,
    categories: ['Colors'],
    summary:
      'Browse tools for selecting colors, editing gradients, checking contrast, and generating palettes.',
    items: [
      {
        label: 'Color Picker',
        fullName: 'Color Picker',
        path: '/color-tools/color-picker',
        icon: <PaintBucket />,
        tags: ['Color Shades'],
        summary:
          'Pick a color, inspect its HEX, RGB, or HSL values, and generate lighter, darker, desaturated, or complementary colors.',
      },
      {
        label: 'Gradient Editor',
        fullName: 'Color Gradient Editor',
        path: '/color-tools/gradient-editor',
        icon: <Rainbow />,
        tags: [
          'CSS Gradient',
          'Gradient to Image',
          'Gradient to png',
          'Gradient to jpeg',
          'Gradient to webp',
        ],
        summary:
          'Create and preview linear or radial CSS gradients, then export the result as CSS or a PNG, JPEG, or WebP image.',
      },
      {
        label: 'Contrast Checker',
        fullName: 'Color Contrast Checker',
        path: '/color-tools/contrast-checker',
        icon: <Baseline />,
        sourceUrl: 'https://www.npmjs.com/package/tinycolor2',
        summary:
          'Check foreground and background color pairs against WCAG AA and AAA contrast requirements.',
      },
      {
        label: 'Palette Generator',
        fullName: 'Color Palette Generator',
        path: '/color-tools/palette-generator',
        icon: <SwatchBook />,
        tags: ['Color Palette', 'Chakra UI v3', 'CSS Palette'],
        summary: `Build color palettes for light and dark themes, preview them, and export CSS or Chakra UI tokens.`,
      },
    ],
  },

  {
    label: 'CSS Tools',
    path: '/css-tools',
    icon: <SiCss />,
    categories: ['CSS'],
    items: [
      {
        label: 'CSS Triangle',
        path: '/css-tools/css-triangle',
        fullName: 'CSS Triangle Generator',
        icon: <Triangle />,
        summary:
          'Generate triangles and arrows from CSS borders, preview their shape, and use the CSS in tooltips or other interface accents.',
      },
      {
        label: 'CSS Unit Converter',
        path: '/css-tools/css-unit-converter',
        icon: <SquaresUnite />,
        tags: ['px to rem', 'rem to px', 'px to em', 'em to px', 'rem to em', 'em to rem'],
        sourceUrl: 'https://github.com/ArthurArakelyan/css-unit-converter-js',
        summary:
          'Convert between CSS units such as px, rem, em, vw, and vh for responsive layouts.',
      },
      {
        label: 'Smooth Shadow Editor',
        path: '/css-tools/smooth-shadow-editor',
        fullName: 'CSS Smooth Shadow Editor',
        tags: ['Smooth Shadow Generator'],
        icon: <BsShadows />,
        summary:
          'Build layered CSS box-shadows and adjust color, blur, opacity, distance, and layers while previewing the result.',
      },
      {
        label: 'Background Pattern Generator',
        path: '/css-tools/css-background-pattern-generator',
        fullName: 'CSS Background Pattern Generator',
        icon: <TbBackground />,
        summary:
          'Create CSS background patterns by adjusting colors, shapes, and sizes, with a live preview as you work.',
      },
    ],
  },

  {
    label: 'Convert',
    path: '/convert',
    icon: <TbReplace />,
    items: [
      {
        label: 'HTML',
        path: '/convert/html',
        fullName: 'Convert HTML',
        icon: <SiHtml5 />,
        categories: ['Code Converters'],
        items: [
          {
            label: 'to JSX',
            fullName: 'Convert HTML to JSX',
            pageTitle: 'HTML to JSX',
            path: '/convert/html/jsx',
            icon: <TbFileTypeJsx />,
            summary: `Convert HTML markup to JSX for use in React components.`,
          },
          {
            label: 'to Markdown',
            fullName: 'Convert HTML to Markdown',
            pageTitle: 'HTML to Markdown',
            path: '/convert/html/markdown',
            icon: <SiMarkdown />,
            summary: `Turn HTML content into Markdown while keeping its document structure readable.`,
          },
        ],
      },
      {
        label: 'SVG',
        path: '/convert/svg',
        fullName: 'Convert SVG',
        icon: <SiSvg />,
        categories: ['Code Converters'],
        items: [
          {
            label: 'to Optimized SVG',
            fullName: 'Convert SVG to Optimized SVG',
            pageTitle: 'SVG to Optimized SVG',
            path: '/convert/svg/optimize',
            icon: <SiSvg />,
            summary: `Optimize SVG markup by removing unnecessary metadata and comments to reduce file size.`,
          },
          {
            label: 'to React',
            fullName: 'Convert SVG to React',
            pageTitle: 'SVG to React',
            path: '/convert/svg/react',
            icon: <SiReact />,
            summary: `Convert SVG markup into a reusable React component with JSX-compatible attributes.`,
          },
          {
            label: 'to Data URI',
            fullName: 'Convert SVG to Data URI',
            pageTitle: 'SVG to Data URI',
            path: '/convert/svg/data-uri',
            summary: `Encode SVG markup as a Base64 data URI for use in CSS backgrounds or HTML attributes.`,
            icon: <TbNumber64Small />,
          },
        ],
      },
      {
        label: 'JSON',
        path: '/convert/json',
        fullName: 'Convert JSON',
        icon: <LuFileJson2 />,
        categories: ['Data Converters'],
        items: [
          {
            label: 'to JSON Schema',
            fullName: 'Convert JSON to JSON Schema',
            pageTitle: 'JSON to JSON Schema',
            path: '/convert/json/json-schema',
            icon: <SiJson />,
            summary:
              'Create a JSON Schema from a sample JSON object to use as a starting point for data validation.',
          },
          {
            label: 'to TypeScript',
            fullName: 'Convert JSON to TypeScript',
            pageTitle: 'JSON to TypeScript',
            path: '/convert/json/typescript',
            icon: <SiTypescript />,
            summary:
              'Generate TypeScript interfaces from a JSON sample, including types for its nested objects and arrays.',
          },
          {
            label: 'to Flow',
            fullName: 'Convert JSON to Flow',
            pageTitle: 'JSON to Flow',
            path: '/convert/json/flow',
            summary:
              'Generate Flow type definitions from a JSON sample, including types for nested values.',
          },
          {
            label: 'to JSDoc',
            fullName: 'Convert JSON to JSDoc',
            pageTitle: 'JSON to JSDoc',
            path: '/convert/json/jsdoc',
            icon: <SiReadthedocs />,
            summary:
              'Create JSDoc type definitions from a JSON sample to document the shape of its data.',
          },
          {
            label: 'to Zod',
            fullName: 'Convert JSON to Zod',
            pageTitle: 'JSON to Zod',
            path: '/convert/json/zod',
            icon: <SiZod />,
            summary: 'Build a Zod schema from a JSON sample to use for runtime validation.',
          },
          {
            label: 'to React Prop Types',
            fullName: 'Convert JSON to React Prop Types',
            pageTitle: 'JSON to React Prop Types',
            path: '/convert/json/react-prop-types',
            icon: <SiReact />,
            summary:
              'Generate React PropTypes definitions from a JSON object for validating component props.',
          },
          {
            label: 'to C#',
            fullName: 'Convert JSON to C#',
            pageTitle: 'JSON to C#',
            path: '/convert/json/c-sharp',
            icon: <SiSharp />,
            summary:
              'Generate C# classes from a JSON sample, with properties based on its data structure.',
          },
          {
            label: 'to Rust',
            fullName: 'Convert JSON to Rust',
            pageTitle: 'JSON to Rust',
            path: '/convert/json/rust',
            icon: <SiRust />,
            summary:
              'Generate Rust structs from a JSON sample, with fields based on its data structure.',
          },
          {
            label: 'to Python',
            fullName: 'Convert JSON to Python',
            pageTitle: 'JSON to Python',
            path: '/convert/json/python',
            icon: <SiPython />,
            summary:
              'Generate Python classes from a JSON sample, with attributes based on its data structure.',
          },
          {
            label: 'to Go',
            fullName: 'Convert JSON to Go',
            pageTitle: 'JSON to Go',
            path: '/convert/json/go',
            icon: <TbBrandGolang />,
            summary:
              'Generate Go structs from a JSON sample, with fields based on its data structure.',
          },
          {
            label: 'to Dart',
            fullName: 'Convert JSON to Dart',
            pageTitle: 'JSON to Dart',
            path: '/convert/json/dart',
            icon: <SiDart />,
            summary:
              'Generate Dart types from a JSON sample, including nested objects and collection fields.',
          },
          {
            label: 'to Elixir',
            fullName: 'Convert JSON to Elixir',
            pageTitle: 'JSON to Elixir',
            path: '/convert/json/elixir',
            icon: <SiElixir />,
            summary: 'Generate Elixir data structures from a JSON sample.',
          },
          {
            label: 'to GraphQL',
            fullName: 'Convert JSON to GraphQL',
            pageTitle: 'JSON to GraphQL',
            path: '/convert/json/graphql',
            icon: <SiGraphql />,
            summary: 'Build GraphQL schema definitions from a JSON sample and its nested data.',
          },
          {
            label: 'to MySQL',
            fullName: 'Convert JSON to MySQL',
            pageTitle: 'JSON to MySQL',
            path: '/convert/json/mysql',
            icon: <SiMysql />,
            summary: 'Create MySQL table definitions from a JSON sample.',
          },
          {
            label: 'to Mongoose Schema',
            fullName: 'Convert JSON to Mongoose Schema',
            pageTitle: 'JSON to Mongoose Schema',
            path: '/convert/json/mongoose',
            icon: <SiMongoose />,
            summary:
              'Generate a Mongoose schema from a JSON sample for use with Node.js and MongoDB.',
          },
          {
            label: 'to BigQuery',
            fullName: 'Convert JSON to BigQuery',
            pageTitle: 'JSON to BigQuery',
            path: '/convert/json/bigquery',
            icon: <SiGooglebigquery />,
            summary: 'Convert a JSON sample into BigQuery SQL for defining a table schema.',
          },
          {
            label: 'to TOML',
            fullName: 'Convert JSON to TOML',
            pageTitle: 'JSON to TOML',
            path: '/convert/json/toml',
            icon: <SiToml />,
            summary:
              'Convert JSON data to TOML while preserving its nested structure where the formats allow.',
          },
          {
            label: 'to YAML',
            fullName: 'Convert JSON to YAML',
            pageTitle: 'JSON to YAML',
            path: '/convert/json/yaml',
            icon: <SiYaml />,
            summary:
              'Convert JSON data to YAML while preserving its nested structure where the formats allow.',
          },
          {
            label: 'to TOON',
            fullName: 'Convert JSON to TOON',
            pageTitle: 'JSON to TOON',
            path: '/convert/json/toon',
            summary:
              'Convert JSON data to TOON, a compact format for representing structured data.',
          },
        ],
      },
      {
        label: 'CSS',
        path: '/convert/css',
        fullName: 'Convert CSS',
        icon: <SiCss />,
        categories: ['Code Converters'],
        items: [
          {
            label: 'to JavaScript',
            fullName: 'Convert CSS to JavaScript',
            pageTitle: 'CSS to JavaScript',
            path: '/convert/css/js',
            icon: <SiJavascript />,
            summary:
              'Convert CSS declarations into JavaScript style objects for use in JavaScript code.',
            serverAction: true,
          },
          {
            label: 'to SCSS',
            fullName: 'Convert CSS to SCSS',
            pageTitle: 'CSS to SCSS',
            path: '/convert/css/scss',
            icon: <SiSass />,
            summary: 'Convert CSS rules to SCSS syntax for continued editing with Sass.',
            serverAction: true,
          },
          {
            label: 'to Tailwind V3',
            fullName: 'Convert CSS to Tailwind V3',
            pageTitle: 'CSS to Tailwind V3',
            path: '/convert/css/tailwind-v3',
            icon: <SiTailwindcss />,
            summary: `Translate CSS styles into Tailwind CSS v3 utility classes.`,
            serverAction: true,
          },
        ],
      },
      {
        label: 'SCSS',
        path: '/convert/scss',
        fullName: 'Convert SCSS',
        icon: <SiSass />,
        categories: ['Code Converters'],
        items: [
          {
            label: 'to CSS',
            fullName: 'Convert SCSS to CSS',
            pageTitle: 'SCSS to CSS',
            path: '/convert/scss/css',
            icon: <SiCss />,
            summary: 'Compile SCSS into CSS for use in a browser or stylesheet.',
          },
          {
            label: 'to JavaScript',
            fullName: 'Convert SCSS to JavaScript',
            pageTitle: 'SCSS to JavaScript',
            path: '/convert/scss/js',
            icon: <SiJavascript />,
            summary: 'Convert SCSS styles into JavaScript style objects for use in an application.',
          },
          {
            label: 'to Tailwind V3',
            fullName: 'Convert SCSS to Tailwind V3',
            pageTitle: 'SCSS to Tailwind V3',
            path: '/convert/scss/tailwind-v3',
            icon: <SiTailwindcss />,
            summary: 'Translate SCSS styles into Tailwind CSS v3 utility classes.',
          },
        ],
      },
      {
        label: 'TypeScript',
        path: '/convert/ts',
        fullName: 'Convert TypeScript',
        icon: <SiTypescript />,
        categories: ['Code Converters'],
        items: [
          {
            label: 'to JSON Schema',
            fullName: 'Convert TypeScript to JSON Schema',
            pageTitle: 'TypeScript to JSON Schema',
            path: '/convert/ts/json-schema',
            icon: <SiJson />,
            summary: 'Create a JSON Schema from TypeScript interfaces or type declarations.',
          },
          {
            label: 'to Zod',
            fullName: 'Convert TypeScript to Zod',
            pageTitle: 'TypeScript to Zod',
            path: '/convert/ts/zod',
            icon: <SiZod />,
            summary:
              'Build a Zod schema from TypeScript interfaces or type declarations for runtime validation.',
          },
          {
            label: 'to JavaScript',
            fullName: 'Convert TypeScript to JavaScript',
            pageTitle: 'TypeScript to JavaScript',
            path: '/convert/ts/javascript',
            icon: <SiJavascript />,
            summary: 'Remove TypeScript type annotations and convert the code to JavaScript.',
          },
        ],
      },
      {
        label: 'JSS',
        path: '/convert/jss',
        fullName: 'Convert JSS',
        icon: <SiJss />,
        categories: ['Code Converters'],
        items: [
          {
            label: 'to CSS',
            fullName: 'Convert JSS to CSS',
            pageTitle: 'JSS to CSS',
            path: '/convert/jss/css',
            icon: <SiCss />,
            summary: 'Convert JavaScript Style Sheets (JSS) rules into CSS.',
          },
          {
            label: 'to SCSS',
            fullName: 'Convert JSS to SCSS',
            pageTitle: 'JSS to SCSS',
            path: '/convert/jss/scss',
            icon: <SiSass />,
            summary: 'Convert JavaScript Style Sheets (JSS) rules into SCSS syntax.',
          },
          {
            label: 'to Tailwind V3',
            fullName: 'Convert JSS to Tailwind V3',
            pageTitle: 'JSS to Tailwind V3',
            path: '/convert/jss/tailwind-v3',
            icon: <SiTailwindcss />,
            summary: `Translate JavaScript Style Sheets (JSS) rules into Tailwind CSS v3 utility classes.`,
          },
        ],
      },
      {
        label: 'TOML',
        path: '/convert/toml',
        fullName: 'Convert TOML',
        icon: <SiToml />,
        categories: ['Data Converters'],
        items: [
          {
            label: 'to JSON',
            fullName: 'Convert TOML to JSON',
            pageTitle: 'TOML to JSON',
            path: '/convert/toml/json',
            icon: <LuFileJson2 />,
            summary:
              'Convert TOML data to JSON for use in tools and applications that expect JSON.',
          },
          {
            label: 'to JSON Schema',
            fullName: 'Convert TOML to JSON Schema',
            pageTitle: 'TOML to JSON Schema',
            path: '/convert/toml/jsschema',
            icon: <SiJson />,
            summary: 'Create a JSON Schema from a TOML sample to describe its data structure.',
          },
          {
            label: 'to YAML',
            fullName: 'Convert TOML to YAML',
            pageTitle: 'TOML to YAML',
            path: '/convert/toml/yaml',
            icon: <SiYaml />,
            summary:
              'Convert TOML data to YAML while preserving its nested structure where the formats allow.',
          },
          {
            label: 'to TypeScript',
            fullName: 'Convert TOML to TypeScript',
            pageTitle: 'TOML to TypeScript',
            path: '/convert/toml/ts',
            icon: <SiTypescript />,
            summary: 'Generate TypeScript interfaces from a TOML sample and its data structure.',
          },
          {
            label: 'to JSDoc',
            fullName: 'Convert TOML to JSDoc',
            pageTitle: 'TOML to JSDoc',
            path: '/convert/toml/jsdoc',
            icon: <SiReadthedocs />,
            summary:
              'Create JSDoc type definitions from a TOML sample to document its data structure.',
          },
        ],
      },
      {
        label: 'YAML',
        path: '/convert/yaml',
        fullName: 'Convert YAML',
        icon: <SiYaml />,
        categories: ['Data Converters'],
        items: [
          {
            label: 'to JSON',
            fullName: 'Convert YAML to JSON',
            pageTitle: 'YAML to JSON',
            path: '/convert/yaml/json',
            icon: <LuFileJson2 />,
            summary:
              'Convert YAML data to JSON for use in tools and applications that expect JSON.',
          },
          {
            label: 'to JSON Schema',
            fullName: 'Convert YAML to JSON Schema',
            pageTitle: 'YAML to JSON Schema',
            path: '/convert/yaml/jsschema',
            icon: <SiJson />,
            summary: 'Create a JSON Schema from a YAML sample to describe its data structure.',
          },
          {
            label: 'to TOML',
            fullName: 'Convert YAML to TOML',
            pageTitle: 'YAML to TOML',
            path: '/convert/yaml/toml',
            icon: <SiToml />,
            summary:
              'Convert YAML data to TOML while preserving its nested structure where the formats allow.',
          },
          {
            label: 'to TypeScript',
            fullName: 'Convert YAML to TypeScript',
            pageTitle: 'YAML to TypeScript',
            path: '/convert/yaml/ts',
            icon: <SiTypescript />,
            summary: 'Generate TypeScript interfaces from a YAML sample and its data structure.',
          },
          {
            label: 'to JSDoc',
            fullName: 'Convert YAML to JSDoc',
            pageTitle: 'YAML to JSDoc',
            path: '/convert/yaml/jsdoc',
            icon: <SiReadthedocs />,
            summary:
              'Create JSDoc type definitions from a YAML sample to document its data structure.',
          },
        ],
      },
      {
        label: 'PHP',
        path: '/convert/php',
        fullName: 'Convert PHP',
        icon: <SiPhp />,
        categories: ['Data Converters'],
        items: [
          {
            label: 'to Serialized Data',
            fullName: 'Convert Data to PHP Serialized Data',
            pageTitle: 'Data to PHP Serialized Data',
            path: '/convert/php/serialized',
            summary:
              'Serialize arrays or objects into the PHP serialized string format for storage or data exchange.',
            icon: <SiPhp />,
          },
          {
            label: 'to De-Serialized Data',
            fullName: 'Convert PHP Serialized Data to De-Serialized Data',
            pageTitle: 'PHP Serialized Data to De-Serialized Data',
            path: '/convert/php/deserialized',
            summary:
              'Decode a PHP-serialized string into readable data for inspection or further use.',
            icon: <Database />,
          },
        ],
      },
    ],
  },

  {
    label: 'Image Tools',
    path: '/image-tools',
    // eslint-disable-next-line jsx-a11y/alt-text
    icon: <Image />,
    categories: ['Utilities'],
    items: [
      {
        label: 'Placeholder Image Generator',
        path: '/image-tools/placeholder-image-generator',
        tags: ['Dummy Image', 'Mock Image'],
        icon: <PiPlaceholder />,
        summary:
          'Create placeholder images by setting their dimensions, background color, and text in your browser.',
      },
      {
        label: 'Image Compressor',
        path: '/image-tools/image-compressor',
        tags: ['Image Optimizer', 'Compress PNG', 'Compress JPEG', 'Compress WebP'],
        icon: <LuImageDown />,
        summary:
          'Compress PNG, JPEG, or WebP images to reduce file size while adjusting output quality.',
        sourceUrl: 'https://www.npmjs.com/package/compressorjs',
      },
      {
        label: 'Image Converter',
        path: '/image-tools/image-converter',
        tags: ['Convert WebP to JPEG', 'Convert PNG to WebP', 'Image Format Converter'],
        icon: <PiImagesSquareBold />,
        summary: 'Convert images between supported formats, including WebP, JPEG, and PNG.',
        sourceUrl: 'https://www.npmjs.com/package/compressorjs',
      },
      {
        label: 'Image Resizer',
        path: '/image-tools/image-resizer',
        tags: ['Resize Image', 'Scale Image', 'Change Dimensions'],
        icon: <Maximize />,
        summary: 'Resize an image by entering new dimensions or scaling it by a percentage.',
      },
      {
        label: 'Image Cropper',
        path: '/image-tools/image-cropper',
        tags: ['Crop Image', 'Aspect Ratio', 'Trim Image'],
        icon: <Crop />,
        summary: 'Crop an image to a preset aspect ratio or choose the crop dimensions yourself.',
        sourceUrl: 'https://www.npmjs.com/package/react-image-crop',
      },
    ],
  },

  {
    label: 'Other Tools',
    path: '/other-tools',
    icon: <ToolCase />,
    categories: ['Utilities'],
    items: [
      {
        label: 'Markdown Editor',
        path: '/other-tools/markdown-editor',
        tags: ['Markdown Viewer', 'Markdown Preview', 'Readme Preview', 'Readme Viewer'],
        summary: `Write Markdown and preview the rendered document as you edit.`,
        icon: <SiMarkdown />,
      },
      {
        label: 'UUID Generator',
        path: '/other-tools/uuid-generator',
        tags: [
          'Unique ID Generator',
          'Random UUID',
          'Random ID',
          'Time based UUID',
          'Time based ID',
        ],
        sourceUrl: 'https://www.npmjs.com/package/uuid',
        icon: <Fingerprint />,
        summary:
          'Generate UUIDs using the versions supported by the tool, with options suited to different identifier needs.',
      },
      {
        label: 'URL Parser',
        path: '/other-tools/url-parser',
        tags: ['Query params'],
        summary: 'Parse a URL into its protocol, hostname, path, query parameters, and fragment.',
        icon: <Link2 />,
      },
      {
        label: 'Base64 File / Image Encoder',
        path: '/other-tools/base64-file-encoder',
        tags: [
          'Convert a File to Base64',
          'Convert an Image to Base64',
          'Convert a File to Data URI',
          'Convert an Image to Data URI',
        ],
        icon: <FileUp />,
        summary: 'Encode a file as Base64 text for data transfer or embedding in HTML and CSS.',
      },
      {
        label: 'Base64 File / Image Decoder',
        path: '/other-tools/base64-file-decoder',
        tags: [
          'Convert a Base64 to File',
          'Convert a Base64 to an Image',
          'Convert a Data URI to File',
          'Convert a Data URI to an Image',
        ],
        icon: <FileDown />,
        summary: 'Decode a Base64 string into a file you can view or download.',
      },
      {
        label: 'QR Code Generator',
        path: '/other-tools/qr-code',
        icon: <QrCode />,
        sourceUrl: 'https://github.com/kozakdenys/qr-code-styling',
        summary:
          'Create QR codes for URLs, Wi-Fi, contact details, messages, and other supported data, with optional colors and logos.',
      },
      {
        label: 'Lorem Ipsum Generator',
        path: '/other-tools/random-text',
        tags: ['Random Text Generator'],
        icon: <Type />,
        summary:
          'Generate Lorem Ipsum placeholder text for page layouts, mockups, and design previews.',
      },
      {
        label: 'Word Counter',
        path: '/other-tools/word-counter',
        tags: ['Sentence Counter', 'Text Counter'],
        icon: <WholeWord />,
        summary: 'Count words, characters, and sentences in a block of text.',
      },
      {
        label: 'JSON Editor',
        path: '/other-tools/json-editor',
        tags: ['JSON Viewer', 'JSON Validator'],
        icon: <FileBraces />,
        sourceUrl: 'https://www.npmjs.com/package/vanilla-jsoneditor',
        summary: 'View, edit, and format JSON in a tree or code editor, with schema validation.',
      },
      {
        label: 'Data Size Converter',
        path: '/other-tools/data-size-converter',
        fullName: 'Data Size Converter',
        tags: ['File Size Converter'],
        icon: <Database />,
        summary: `Convert data sizes across bit and byte units using either decimal (1000) or binary (1024) calculations.`,
      },
      {
        label: 'CSP Generator',
        path: '/other-tools/csp-header-generator',
        fullName: 'Content Security Policy Header Generator',
        tags: ['CSP', 'Header Generator'],
        icon: <Shield />,
        summary:
          'Build a Content Security Policy header using directive groups, service presets, and script or style hashes.',
      },
    ],
  },
]);
